# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x05tesla\"`\n\x0bVehicleData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x15\n\rvehicle_speed\x18\x02 \x01(\x02\x12\x15\n\rbattery_level\x18\x03 \x01(\x02\x12\x10\n\x08power_kw\x18\x04 \x01(\x02\"H\n\x0eTelemetryBatch\x12#\n\x07records\x18\x01 \x03(\x0b\x32\x12.tesla.VehicleData\x12\x11\n\tdevice_id\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VEHICLEDATA._serialized_start=26
  _VEHICLEDATA._serialized_end=122
  _TELEMETRYBATCH._serialized_start=124
  _TELEMETRYBATCH._serialized_end=196
# @@protoc_insertion_point(module_scope)
